const mongoose = require('mongoose');
const dotenv = require('dotenv');
dotenv.config();

const Course = require('../models/Course');
const User = require('../models/User');

const courses = [
  { title: 'Machine Learning A-Z with Python', description: 'Complete ML bootcamp: supervised, unsupervised learning, neural networks, and real projects.', instructor: 'Dr. Sarah Chen', category: 'AI', tags: ['machine learning', 'python', 'sklearn', 'tensorflow'], level: 'intermediate', duration: 42, totalLessons: 180, rating: 4.8, reviewCount: 12400, enrolledCount: 87500, featured: true, skills: ['Python', 'Scikit-learn', 'TensorFlow', 'Data Analysis'], isFree: false, price: 1299, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400' },
  { title: 'Full Stack React & Node.js', description: 'Build production-ready MERN apps with auth, REST APIs, MongoDB, and deployment.', instructor: 'Alex Rivera', category: 'Web Development', tags: ['react', 'nodejs', 'mongodb', 'express', 'javascript'], level: 'intermediate', duration: 56, totalLessons: 220, rating: 4.9, reviewCount: 18900, enrolledCount: 124000, featured: true, skills: ['React', 'Node.js', 'MongoDB', 'REST API'], isFree: false, price: 1499, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?w=400' },
  { title: 'Data Science with Python & Pandas', description: 'From data cleaning to visualization and statistical analysis. Real datasets included.', instructor: 'Maya Patel', category: 'Data Science', tags: ['python', 'pandas', 'numpy', 'matplotlib', 'data analysis'], level: 'beginner', duration: 35, totalLessons: 140, rating: 4.7, reviewCount: 9800, enrolledCount: 65000, featured: true, skills: ['Python', 'Pandas', 'NumPy', 'Matplotlib'], isFree: true, price: 0, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400' },
  { title: 'Ethical Hacking & Penetration Testing', description: 'Learn cybersecurity from scratch: network hacking, web exploitation, and CTF challenges.', instructor: 'James Okafor', category: 'Cybersecurity', tags: ['ethical hacking', 'kali linux', 'pentesting', 'network security'], level: 'advanced', duration: 48, totalLessons: 195, rating: 4.8, reviewCount: 7600, enrolledCount: 42000, featured: true, skills: ['Kali Linux', 'Network Security', 'Web Exploitation'], isFree: false, price: 1799, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400' },
  { title: 'AWS Cloud Practitioner + Solutions Architect', description: 'Master AWS from fundamentals to advanced architecture. Exam prep included.', instructor: 'Priya Sharma', category: 'Cloud', tags: ['aws', 'cloud', 'devops', 'infrastructure'], level: 'intermediate', duration: 38, totalLessons: 155, rating: 4.6, reviewCount: 11200, enrolledCount: 78000, featured: false, skills: ['AWS', 'Cloud Architecture', 'DevOps'], isFree: false, price: 1599, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1606765962248-7ff407b51667?w=400' },
  { title: 'Flutter Mobile App Development', description: 'Build beautiful cross-platform apps for iOS and Android with Flutter and Dart.', instructor: 'Lucas Kim', category: 'Mobile', tags: ['flutter', 'dart', 'mobile', 'ios', 'android'], level: 'beginner', duration: 30, totalLessons: 120, rating: 4.7, reviewCount: 8300, enrolledCount: 51000, featured: false, skills: ['Flutter', 'Dart', 'Mobile Dev'], isFree: false, price: 999, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400' },
  { title: 'Deep Learning & Neural Networks', description: 'Advanced DL with PyTorch: CNNs, RNNs, transformers, and production deployment.', instructor: 'Dr. Sarah Chen', category: 'AI', tags: ['deep learning', 'pytorch', 'cnn', 'rnn', 'transformers'], level: 'advanced', duration: 55, totalLessons: 210, rating: 4.9, reviewCount: 6500, enrolledCount: 38000, featured: true, skills: ['PyTorch', 'Deep Learning', 'Computer Vision', 'NLP'], isFree: false, price: 1999, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=400' },
  { title: 'JavaScript: Zero to Expert', description: 'Complete modern JavaScript from basics to advanced: ES6+, async, OOP, and DSA.', instructor: 'Emma Wilson', category: 'Web Development', tags: ['javascript', 'es6', 'async', 'dom', 'oop'], level: 'beginner', duration: 68, totalLessons: 280, rating: 4.8, reviewCount: 22400, enrolledCount: 156000, featured: true, skills: ['JavaScript', 'ES6+', 'DOM', 'Async Programming'], isFree: false, price: 1299, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?w=400' },
  { title: 'SQL & Database Design Masterclass', description: 'PostgreSQL, MySQL, query optimization, indexing, and schema design for real applications.', instructor: 'Tom Zhang', category: 'Data Science', tags: ['sql', 'postgresql', 'database', 'query optimization'], level: 'beginner', duration: 22, totalLessons: 88, rating: 4.6, reviewCount: 13100, enrolledCount: 92000, featured: false, skills: ['SQL', 'PostgreSQL', 'Database Design'], isFree: true, price: 0, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=400' },
  { title: 'Network Security & Defense', description: 'Firewalls, IDS/IPS, VPNs, SOC fundamentals, and real-world threat analysis.', instructor: 'James Okafor', category: 'Cybersecurity', tags: ['network security', 'firewall', 'vpn', 'soc', 'threat analysis'], level: 'intermediate', duration: 32, totalLessons: 130, rating: 4.5, reviewCount: 5200, enrolledCount: 29000, featured: false, skills: ['Network Security', 'Firewall Config', 'Threat Analysis'], isFree: false, price: 1399, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400' },
  { title: 'Google Cloud Professional Engineer', description: 'GCP deep dive: Compute, Storage, Big Query, Kubernetes, and exam prep.', instructor: 'Priya Sharma', category: 'Cloud', tags: ['gcp', 'google cloud', 'kubernetes', 'bigquery'], level: 'advanced', duration: 45, totalLessons: 180, rating: 4.7, reviewCount: 4800, enrolledCount: 31000, featured: false, skills: ['GCP', 'Kubernetes', 'BigQuery'], isFree: false, price: 1699, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400' },
  { title: 'React Native: Build iOS & Android Apps', description: 'Cross-platform mobile development with React Native, Expo, and Firebase.', instructor: 'Lucas Kim', category: 'Mobile', tags: ['react native', 'expo', 'firebase', 'mobile'], level: 'intermediate', duration: 36, totalLessons: 148, rating: 4.6, reviewCount: 6900, enrolledCount: 44000, featured: false, skills: ['React Native', 'Expo', 'Firebase'], isFree: false, price: 1099, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=400' },
  { title: 'NLP with Transformers & BERT', description: 'Text classification, sentiment analysis, QA systems using HuggingFace transformers.', instructor: 'Dr. Sarah Chen', category: 'AI', tags: ['nlp', 'bert', 'transformers', 'huggingface', 'text classification'], level: 'advanced', duration: 28, totalLessons: 110, rating: 4.8, reviewCount: 3400, enrolledCount: 22000, featured: false, skills: ['NLP', 'BERT', 'HuggingFace', 'Text Processing'], isFree: false, price: 1599, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=400' },
  { title: 'Next.js & TypeScript Production Apps', description: 'SSR, SSG, API routes, authentication, and deployment on Vercel with TypeScript.', instructor: 'Alex Rivera', category: 'Web Development', tags: ['nextjs', 'typescript', 'ssr', 'vercel', 'react'], level: 'intermediate', duration: 40, totalLessons: 160, rating: 4.7, reviewCount: 8900, enrolledCount: 58000, featured: false, skills: ['Next.js', 'TypeScript', 'SSR', 'Vercel'], isFree: false, price: 1299, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1593720219276-0b1eacd0aef4?w=400' },
  { title: 'Power BI & Data Visualization', description: 'Build executive-grade dashboards, reports, and real-time analytics with Power BI.', instructor: 'Maya Patel', category: 'Data Science', tags: ['power bi', 'data visualization', 'business intelligence', 'dax'], level: 'beginner', duration: 20, totalLessons: 80, rating: 4.5, reviewCount: 7200, enrolledCount: 48000, featured: false, skills: ['Power BI', 'DAX', 'Data Visualization'], isFree: true, price: 0, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400' },
  { title: 'Docker & Kubernetes DevOps', description: 'Containerization, orchestration, CI/CD pipelines, Helm charts, and production deployments.', instructor: 'Tom Zhang', category: 'Cloud', tags: ['docker', 'kubernetes', 'devops', 'cicd', 'helm'], level: 'intermediate', duration: 33, totalLessons: 135, rating: 4.8, reviewCount: 9100, enrolledCount: 61000, featured: true, skills: ['Docker', 'Kubernetes', 'CI/CD', 'DevOps'], isFree: false, price: 1499, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=400' },
  { title: 'Android Development with Kotlin', description: 'Build Android apps from scratch with Kotlin, Jetpack Compose, Room DB, and MVVM.', instructor: 'Lucas Kim', category: 'Mobile', tags: ['android', 'kotlin', 'jetpack compose', 'room', 'mvvm'], level: 'intermediate', duration: 38, totalLessons: 152, rating: 4.6, reviewCount: 5600, enrolledCount: 35000, featured: false, skills: ['Kotlin', 'Android', 'Jetpack Compose'], isFree: false, price: 1099, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=400' },
  { title: 'Web3 & Blockchain Development', description: 'Smart contracts, Solidity, DApps, Web3.js, Ethereum, and NFT projects.', instructor: 'Emma Wilson', category: 'Web Development', tags: ['blockchain', 'solidity', 'web3', 'ethereum', 'nft'], level: 'advanced', duration: 44, totalLessons: 175, rating: 4.4, reviewCount: 3800, enrolledCount: 24000, featured: false, skills: ['Solidity', 'Web3.js', 'Smart Contracts', 'Ethereum'], isFree: false, price: 1799, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1644361566696-3d442b5b482a?w=400' },
  { title: 'Python for Beginners: Complete Bootcamp', description: 'Learn Python from scratch with projects, OOP, file handling, and automation.', instructor: 'Maya Patel', category: 'Data Science', tags: ['python', 'beginner', 'programming', 'oop', 'automation'], level: 'beginner', duration: 25, totalLessons: 100, rating: 4.7, reviewCount: 31000, enrolledCount: 198000, featured: false, skills: ['Python', 'OOP', 'File Handling', 'Automation'], isFree: true, price: 0, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=400' },
  { title: 'Certified Cloud Security Professional', description: 'Cloud security architecture, IAM, compliance (GDPR, SOC2), and threat modeling.', instructor: 'James Okafor', category: 'Cybersecurity', tags: ['cloud security', 'iam', 'gdpr', 'compliance', 'threat modeling'], level: 'advanced', duration: 36, totalLessons: 145, rating: 4.7, reviewCount: 2900, enrolledCount: 18000, featured: false, skills: ['Cloud Security', 'IAM', 'Compliance', 'Threat Modeling'], isFree: false, price: 1899, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=400' }
];

courses.push(
  { title: 'Java Spring Boot Backend Masterclass', description: 'Build secure REST APIs with Spring Boot, JPA, JWT, and production-grade backend patterns.', instructor: 'Arjun Mehta', category: 'Web Development', tags: ['java', 'spring boot', 'rest api', 'jwt', 'backend'], level: 'intermediate', duration: 52, totalLessons: 210, rating: 4.8, reviewCount: 6400, enrolledCount: 47000, featured: false, skills: ['Java', 'Spring Boot', 'JPA', 'REST APIs'], isFree: false, price: 1599, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&q=80&fit=crop' },
  { title: 'C++ Data Structures & Algorithms', description: 'Master DSA, problem solving, and competitive programming with C++ from core concepts to advanced topics.', instructor: 'Neha Verma', category: 'Data Science', tags: ['c++', 'dsa', 'algorithms', 'competitive programming'], level: 'beginner', duration: 46, totalLessons: 190, rating: 4.7, reviewCount: 8100, enrolledCount: 52000, featured: false, skills: ['C++', 'DSA', 'Algorithms', 'Problem Solving'], isFree: true, price: 0, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=1200&q=80&fit=crop' },
  { title: 'Generative AI with ChatGPT & LangChain', description: 'Create AI apps with prompt engineering, RAG, vector databases, and agent workflows.', instructor: 'Dr. Sarah Chen', category: 'AI', tags: ['generative ai', 'chatgpt', 'langchain', 'rag', 'prompt engineering'], level: 'intermediate', duration: 24, totalLessons: 96, rating: 4.9, reviewCount: 5100, enrolledCount: 33000, featured: true, skills: ['Prompt Engineering', 'LangChain', 'RAG', 'Vector Databases'], isFree: false, price: 1799, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=1200&q=80&fit=crop' },
  { title: 'Azure Cloud Fundamentals & Solutions', description: 'Learn Azure compute, storage, networking, IAM, and deployment best practices for cloud projects.', instructor: 'Priya Sharma', category: 'Cloud', tags: ['azure', 'cloud', 'compute', 'storage', 'networking'], level: 'beginner', duration: 34, totalLessons: 138, rating: 4.6, reviewCount: 3900, enrolledCount: 28000, featured: false, skills: ['Azure', 'Cloud Architecture', 'Networking', 'IAM'], isFree: false, price: 1299, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80&fit=crop' },
  { title: 'iOS App Development with Swift', description: 'Build polished iPhone apps with Swift, SwiftUI, and modern Apple development workflows.', instructor: 'Lucas Kim', category: 'Mobile', tags: ['ios', 'swift', 'swiftui', 'mobile', 'apple'], level: 'intermediate', duration: 40, totalLessons: 165, rating: 4.7, reviewCount: 4600, enrolledCount: 25000, featured: false, skills: ['Swift', 'SwiftUI', 'iOS', 'App Design'], isFree: false, price: 1399, certificate: true, thumbnail: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80&fit=crop' }
);

async function seed() {
  try {
    if (mongoose.connection.readyState === 0) {
      await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/careerflow');
    }
    await Course.deleteMany({});
    await Course.insertMany(courses);
    console.log(`✅ Seeded ${courses.length} courses`);

    // Create demo user
    await User.deleteMany({ email: 'demo@careerflow.com' });
    await User.create({ name: 'Demo Learner', email: 'demo@careerflow.com', password: 'demo1234', interests: ['AI', 'Web Development', 'Data Science'], level: 'intermediate', totalPoints: 450, streak: 7 });
    console.log('✅ Demo user created: demo@careerflow.com / demo1234');
    process.exit(0);
  } catch (err) { console.error(err); process.exit(1); }
}

module.exports = { seed, courses };

if (require.main === module) {
  seed();
}
